info:
    namespace: stemcraft
categories:
    graves:
        enabled: true
        icon: "stemcraft:grave"
        name: "Grave"
        items:
            - "stemcraft:grave"
items:
    grave:
        display_name: Grave
        permission: grave
        resource:
            material: STONE
            generate: false
            model_path: item/grave
        behaviours:
            furniture:
                small_hitbox: false
                solid: true
                fixed_rotation: false
                placeable_on:
                    floor: true
                    ceiling: false
                    walls: false
