info:
    namespace: stemcraft
font_images:
    crafting_table:
        show_in_gui: true
        suggest_in_command: false
        path: _font/crafting_table.png
        symbol: "\uE120"
        scale_ratio: 9
        y_position: 8
    enchantment_table:
        show_in_gui: true
        suggest_in_command: false
        path: _font/enchantment_table.png
        symbol: "\uE121"
        scale_ratio: 9
        y_position: 8
    skeleton_head_front:
        show_in_gui: true
        suggest_in_command: false
        path: _font/skeleton_head_front.png
        symbol: "\uE122"
        scale_ratio: 9
        y_position: 8
    chat_bubble:
        show_in_gui: true
        suggest_in_command: false
        path: _font/chat_bubble.png
        symbol: "\uE123"
        scale_ratio: 24
        y_position: 24
    info_purple:
        show_in_gui: false
        suggest_in_command: false
        path: _font/info_purple.png
        symbol: "\uE124"
        scale_ratio: 24
        y_position: 24
    info_blue:
        show_in_gui: false
        suggest_in_command: false
        path: _font/info_blue.png
        symbol: "\uE125"
        scale_ratio: 9
        y_position: 8
    info_green:
        show_in_gui: false
        suggest_in_command: false
        path: _font/info_green.png
        symbol: "\uE126"
        scale_ratio: 24
        y_position: 24
    question_yellow:
        show_in_gui: false
        suggest_in_command: false
        path: _font/question_yellow.png
        symbol: "\uE127"
        scale_ratio: 24
        y_position: 24
    question_blue:
        show_in_gui: false
        suggest_in_command: false
        path: _font/question_blue.png
        symbol: "\uE128"
        scale_ratio: 24
        y_position: 24
    question_green:
        show_in_gui: false
        suggest_in_command: false
        path: _font/question_green.png
        symbol: "\uE129"
        scale_ratio: 24
        y_position: 24
    world:
        show_in_gui: false
        suggest_in_command: false
        path: _font/world.png
        symbol: "\uE12A"
        scale_ratio: 9
        y_position: 8
    location:
        show_in_gui: false
        suggest_in_command: false
        path: _font/location.png
        symbol: "\uE12B"
        scale_ratio: 9
        y_position: 8
    house:
        show_in_gui: false
        suggest_in_command: false
        path: _font/house.png
        symbol: "\uE12C"
        scale_ratio: 9
        y_position: 8
    purple_bed:
        permission: emoji.mcemojis.purple_bed
        show_in_gui: true
        path: _font/purple_bed.png
        symbol: "\uE12D"
        scale_ratio: 9
        y_position: 8
    green_bed:
        permission: emoji.mcemojis.green_bed
        show_in_gui: true
        path: _font/green_bed.png
        symbol: "\uE12E"
        scale_ratio: 9
        y_position: 8
    discord:
        show_in_gui: true
        path: _font/discord.png
        symbol: "\uE12F"
        scale_ratio: 9
        y_position: 8
    warning_yellow:
        show_in_gui: false
        suggest_in_command: false
        path: _font/warning_yellow.png
        symbol: "\uE131"
        scale_ratio: 9
        y_position: 8
    warning_red:
        show_in_gui: false
        suggest_in_command: false
        path: _font/warning_red.png
        symbol: "\uE132"
        scale_ratio: 9
        y_position: 8
    click_action_left:
        show_in_gui: false
        suggest_in_command: false
        path: _font/click_action_left.png
        symbol: "\uE133"
        scale_ratio: 9
        y_position: 8
    click_action_right:
        show_in_gui: false
        suggest_in_command: false
        path: _font/click_action_right.png
        symbol: "\uE134"
        scale_ratio: 9
        y_position: 8
