info:
    namespace: stemcraft
items:
    copper_coin:
        display_name: Copper Coin
        resource:
            material: STICK
            generate: true
            textures:
                - item/copper_coin.png
    iron_coin:
        display_name: Iron Coin
        resource:
            material: STICK
            generate: true
            textures:
                - item/iron_coin.png
    gold_coin:
        display_name: Gold Coin
        resource:
            material: STICK
            generate: true
            textures:
                - item/gold_coin.png
    diamond_coin:
        display_name: Diamond Coin
        resource:
            material: STICK
            generate: true
            textures:
                - item/diamond_coin.png
    emerald_coin:
        display_name: Emerald Coin
        resource:
            material: STICK
            generate: true
            textures:
                - item/emerald_coin.png
    lapis_coin:
        display_name: Lapis Coin
        resource:
            material: STICK
            generate: true
            textures:
                - item/lapis_coin.png
    netherite_coin:
        display_name: Netherite Coin
        resource:
            material: STICK
            generate: true
            textures:
                - item/netherite_coin.png
    ruby_coin:
        display_name: Ruby Coin
        resource:
            material: STICK
            generate: true
            textures:
                - item/ruby_coin.png
