info:
    namespace: stemcraft
font_images:
    role_stemcraft:
        show_in_gui: false
        suggest_in_command: false
        path: _font/roles/stemcraft.png
        symbol: "\uE130"
        scale_ratio: 9
        y_position: 8
    role_stagecraft:
        show_in_gui: false
        suggest_in_command: false
        path: _font/roles/stagecraft.png
        symbol: "\uE135"
        scale_ratio: 9
        y_position: 8

    # staff:
    #     permission: "stemcraft.role.staff"
    #     show_in_gui: true
    #     suggest_in_command: false
    #     path: "font/roles/staff.png"
    #     symbol: "\uE130"
    #     scale_ratio: 9
    #     y_position: 8
    # mod:
    #     permission: "stemcraft.role.mod"
    #     show_in_gui: true
    #     suggest_in_command: false
    #     path: "font/roles/mod.png"
    #     symbol: "\uE131"
    #     scale_ratio: 9
    #     y_position: 8
    # helper:
    #     permission: "stemcraft.role.helper"
    #     show_in_gui: true
    #     suggest_in_command: false
    #     path: "font/roles/helper.png"
    #     symbol: "\uE132"
    #     scale_ratio: 9
    #     y_position: 8
    # knight:
    #     permission: "stemcraft.role.knight"
    #     show_in_gui: true
    #     suggest_in_command: false
    #     path: "font/roles/knight.png"
    #     symbol: "\uE133"
    #     scale_ratio: 9
    #     y_position: 8
    # boost:
    #     permission: "stemcraft.role.boost"
    #     show_in_gui: true
    #     suggest_in_command: false
    #     path: "font/roles/boost.png"
    #     symbol: "\uE134"
    #     scale_ratio: 9
    #     y_position: 8
